[versions]
# libraries
retrofit2 = "3.0.0"
junit-jupiter = "6.1.0"
okhttp3 = "5.4.0"
mockk = "1.14.11"
kotest = "6.1.11"
jgrapht = "1.5.3"
keytar = "1.0.0"
zowe-kotlin-sdk = "1.0.0-rc.1"
dotenv = "6.5.1"
ktor = "3.4.1"
json-schema-validator = "0.5.2"

# plugins
gradle-platform-plugin = "2.16.0"
sonarqube = "7.2.2.6593"
changelog = "2.5.0"
kover = "0.9.8"
dependencycheck = "12.1.9"

[libraries]
# build deps
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
retrofit2-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit2" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
jgrapht-core = { group = "org.jgrapht", name = "jgrapht-core", version.ref = "jgrapht" }
java-keytar = { group = "com.starxg", name = "java-keytar", version.ref = "keytar" }
zowe-kotlin-sdk = { group = "org.zowe.sdk", name = "kotlinsdk", version.ref = "zowe-kotlin-sdk" }
dotenv = { group = "io.github.cdimascio", name = "dotenv-kotlin", version.ref = "dotenv" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
json-schema-validator = { group = "io.github.optimumcode", name = "json-schema-validator", version.ref = "json-schema-validator" }

# test deps
okhttp3-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp3" }
okhttp3-okhttp-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "okhttp3" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }

[plugins]
gradle-platform-plugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradle-platform-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
