package eu.ibagroup.formainframe.dataops.synchronizer

import eu.ibagroup.formainframe.dataops.DataOpsComponentFactory

interface ContentSynchronizerFactory : DataOpsComponentFactory<ContentSynchronizer>